---
title: "Breeds impact on adoption"
author: "Matthew Wilcox, Randy Otoo, Anthony Barrios, Arianne PozziBarba"
output: pdf_document
---

# Libraries

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
library(Rgraphviz)
library(data.tree)
```
# Import and Clean Data

```{r}
animal_intake.df <- read_csv("Louisville_Metro_ky_-_Animal_Service_Intake_and_Outcome.csv")

```

```{r}
dog_intake.df <- animal_intake.df %>% filter(animaltype == "DOG") %>% 
  mutate(indate = str_remove(indate, " .*"),
         outdate = str_remove(outdate, " .*"),
         indate = as.Date(indate, format = "%Y/%m/%d"),
         outdate = as.Date(outdate, format = "%Y/%m/%d"),
         timeHeld = outdate - indate
         )%>%
  filter(intype == "STRAY", 
         outtype != "DISPOSAL") %>%
  select(outtype, sex, bites, petsize, color, breed, timeHeld)


```

# Probability

```{r}
pitbull_adopt_euth <- dog_intake.df %>%
  select(outtype, breed) %>%
  filter(
    outtype == "ADOPTION" | outtype == "EUTH"
  ) %>%
  mutate(breed = case_when(
    grepl("PIT BULL", breed) ~ "Is Pitbull",
    TRUE ~ "Not Pitbull"
  ))%>% group_by(outtype, breed) %>%
  summarise(n = n()) %>%
  pivot_wider(names_from = breed, values_from = n) %>%
  column_to_rownames(., var = "outtype")

pitbull_adopt_euth %>% kbl(caption = "Frequency Table of Pitbull and Adoption") %>%  kable_classic_2(full_width = F)


```

```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("Rgraphviz")
library("Rgraphviz")
```

```{r}
total <- sum(pitbull_adopt_euth)

# Probability of a (Prob is pitbull)
a<- sum(pitbull_adopt_euth[1])/total
 
# Probability (b | a) (Prob Adopted given pitbull)
bGivena<- pitbull_adopt_euth[1,1]/sum(pitbull_adopt_euth[1])
 
# Probability (b | ¬a)
bGivenNota<- pitbull_adopt_euth[1,2]/sum(pitbull_adopt_euth[2])


###################### Everything below here will be calculated
 
# Calculate the rest of the values based upon the 3 variables above
notbGivena<-1-bGivena
notA<-1-a
notbGivenNota<-1-bGivenNota
 
#Joint Probabilities of a and B, a and notb, nota and b, nota and notb
aANDb<-a*bGivena
aANDnotb<-a*notbGivena
notaANDb <- notA*bGivenNota
notaANDnotb <- notA*notbGivenNota
 
# Probability of B
b<- aANDb + notaANDb
notB <- 1-b
 
# Bayes theorum - probabiliyt of A | B
# (a | b) = Prob (a AND b) / prob (b)
aGivenb <- aANDb / b
 
# These are the labels of the nodes on the graph
# To signify "Not A" - we use A' or A prime 
 
node1<-"P"
node2<-"Is Pitbull"
node3<-"Not Pitbull"
node4<-"IS Pitbull & Adopted"
node5<-"Is Pitbull & Euthanized'"
node6<-"Not Pitbull & Adopted"
node7<-"Not Pitbull & Euthanized"
nodeNames<-c(node1,node2,node3,node4, node5,node6, node7)
 
rEG <- new("graphNEL", nodes=nodeNames, edgemode="directed")
#Erase any existing plots
# dev.off()
 
# Draw the "lines" or "branches" of the probability Tree
rEG <- addEdge(nodeNames[1], nodeNames[2], rEG, 1)
rEG <- addEdge(nodeNames[1], nodeNames[3], rEG, 1)
rEG <- addEdge(nodeNames[2], nodeNames[4], rEG, 1)
rEG <- addEdge(nodeNames[2], nodeNames[5], rEG, 1)
rEG <- addEdge(nodeNames[3], nodeNames[6], rEG, 1)
rEG <- addEdge(nodeNames[3], nodeNames[7], rEG, 10)
 
eAttrs <- list()
 
q<-edgeNames(rEG)
 
# Add the probability values to the the branch lines
 
eAttrs$label <- c(toString(round(a,4)),toString(round(notA,4)),
 toString(round(bGivena,4)), toString(round(notbGivena,4)),
 toString(round(bGivenNota,4)), toString(round(notbGivenNota,4)))
names(eAttrs$label) <- c(q[1],q[2], q[3], q[4], q[5], q[6])
edgeAttrs<-eAttrs
 
# Set the color, etc, of the tree
attributes<-list(node=list(label="foo", fillcolor="lightgreen", fontsize="15"),
 edge=list(color="red"),graph=list(rankdir="LR"))
 
#Plot the probability tree using Rgraphvis
plot(rEG, edgeAttrs=eAttrs, attrs=attributes)
nodes(rEG)
edges(rEG)
 
#Add the probability values to the leaves of A&B, A&B', A'&B, A'&B'
text(500,420,round(aANDb,4), cex=.8)
 
text(500,280,round(aANDnotb,4),cex=.8)
 
text(500,160,round(notaANDb,4),cex=.8)
 
text(500,30,round(notaANDnotb,4),cex=.8)
 
text(340,440,"(Adopted | Is Pitbull)",cex=.8)
 
text(340,230,"(Euthanized | Is Pitbull)",cex=.8)
 
#Write a table in the lower left of the probablites of A and B
text(80,50,paste("P(A):",round(a,4)),cex=.9, col="darkgreen")
text(80,20,paste("P(A'):",round(notA,4)),cex=.9, col="darkgreen")
 
text(160,50,paste("P(B):",round(b,digits=4)),cex=.9)
text(160,20,paste("P(B'):",round(notB, 4)),cex=.9)
 
text(80,420,paste("P(A|B): ",round(aGivenb,digits=4)),cex=.9,col="blue")

```  

https://www.harrysurden.com/wordpress/archives/292 refrenced to help build the tree diagram. 


```{r}
pit_adopt2 <- dog_intake.df %>%
  select(outtype, breed) %>%
  filter(
    outtype == "ADOPTION" | outtype == "EUTH"
  ) %>%
  mutate(breed = case_when(
    grepl("PIT BULL", breed) ~ "Is Pitbull",
    TRUE ~ "Not Pitbull"
  ))%>% group_by(outtype, breed) %>%
  summarise(n = n()) 
pit_adopt2 <- pit_adopt2 %>%
  mutate(
    pathString = paste(breed, outtype, sep = "/"),
    prob = case_when(
      breed == "Is Pitbull" ~ n / sum(pit_adopt2$n[pit_adopt2$breed == "Is Pitbull"]),
      breed == "Not Pitbull"  ~ n / sum(pit_adopt2$n[pit_adopt2$breed == "Not Pitbull"])
         )) %>%
  ungroup() %>%
  add_row(outtype = NA, breed = NA, n = NA, pathString = "Is Pitbull", prob = sum(pit_adopt2$n[pit_adopt2$breed == "Is Pitbull"])) %>%
  add_row(outtype = NA, breed = NA, n = NA, pathString = "Not Pitbull", prob = sum(pit_adopt2$n[pit_adopt2$breed == "Not Pitbull"])) %>%
  select(pathString,prob)






```
```{r}
prob_data <- pit_adopt2 %>%  mutate(tree_level = str_count(string = pathString, pattern = "/") + 1,
         tree_group = str_replace(string = pathString, pattern = "/.*", replacement = ""),
         node_type = "decision_node"
  )

max_tree_level <- max(prob_data$tree_level, na.rm = T) 

parent_lookup <- prob_data %>% distinct(pathString, prob) # get distinct probabilities to facilitate finding parent node probability

for (i in 1:(max_tree_level -  1)) { # loop through all tree layers to get all immidiate parent probabilities (to calculate cumulative prob)
  
  names(parent_lookup)[1] <-paste0("parent",i)
  names(parent_lookup)[2] <-paste0("parent_prob",i)
  
  for (j in 1:i) {
    
    if (j == 1)  prob_data[[paste0("parent",i)]] <- sub("/[^/]+$", "", prob_data$pathString)
    else if (j  > 1) prob_data[[paste0("parent",i)]] <- sub("/[^/]+$", "", prob_data[[paste0("parent",i)]])
  }
  
  prob_data <- prob_data %>% left_join(parent_lookup, by = paste0("parent",i))
  
}


prob_data$overall_prob <- apply(prob_data %>% select(contains("prob"))  , 1, prod, na.rm = T)  # calculate cumulative probability   
```

```{r}
terminal_data <- prob_data %>%  filter(tree_level == max_tree_level) %>% # create new rows that will display terminal/final step calulcations on the tree
  mutate(node_type = 'terminal',
         pathString = paste0(pathString, "/overall"),
         prob = NA,
         tree_level = max_tree_level + 1)

start_node <- "weather" # name the root node

prob_data = bind_rows(prob_data, terminal_data) %>%  # bind everything together 
  mutate(pathString = paste0(start_node,"/",pathString),
         overall_prob = ifelse(node_type == 'terminal', overall_prob, NA),
         prob_rank = rank(-overall_prob, ties.method = "min", na.last = "keep"))

prob_data = bind_rows(prob_data, data.frame(pathString = start_node, node_type = 'start', tree_level = 0)) %>% # add one new row to serve as the start node label
  select(-contains("parent"))
```

```{r}
make_my_tree <- function(mydf, display_level = NULL, show_rank = FALSE, direction = "LR") {
  
  if (!is.null(display_level) ) {
    mydf <- mydf %>% filter(tree_level <= display_level)
    
  }
  
  mytree <- as.Node(mydf) 
  
  GetEdgeLabel <- function(node) switch(node$node_type, node$prob)
  
  GetNodeShape <- function(node) switch(node$node_type, start = "box", node_decision = "circle", terminal = "none")
  
  
  GetNodeLabel <- function(node) switch(node$node_type, 
                                        terminal = ifelse(show_rank  == TRUE, paste0("Prob: ", node$overall_prob,"\nRank: ", node$prob_rank),
                                                          paste0("Prob: ", node$overall_prob)),
                                        node$node_name)
  
  SetEdgeStyle(mytree, fontname = 'helvetica', label = GetEdgeLabel)
  
  SetNodeStyle(mytree, fontname = 'helvetica', label = GetNodeLabel, shape = GetNodeShape)
  
  SetGraphStyle(mytree, rankdir = direction) 
  
  plot(mytree)
  
}
```

```{r}
library(DiagrammeR)
make_my_tree(prob_data)
```